<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AssimpNet" Version="5.0.0-beta1" />
      <PackageReference Include="OpenTK" Version="4.9.4" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Assets/Shaders/**" CopyToOutputDirectory="PreserveNewest" />
        <None Include="Assets/Textures/**" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Sprites\sprite.png">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Sprites\bg.png">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Sprites\pole.png">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Models\tree01.fbx" />
      <None Remove="Assets\Models\tree02_winter.fbx" />
      <None Remove="Assets\Models\tree02.fbx" />
      <None Remove="Assets\Models\tree12.fbx" />
      <None Remove="Assets\Models\house.fbx" />
      <None Remove="Assets\Models\fence.fbx" />
      <None Remove="Assets\Models\lamp.fbx" />
      <None Remove="Assets\Models\skeleton.fbx" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Sprites\" />
    </ItemGroup>
</Project>
